name: Solidity

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./solidity

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          cd ./optics-core
          npm i
          cd ../optics-xapps
          npm i
          cd ../../typescript/optics-tests
          npm i
          cd ../optics-deploy
          npm i
          cd ../typechain
          npm i

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./solidity

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: |
          cd ./optics-core
          npm run lint
          cd ../optics-xapps
          npm run lint

  test:
    env:
      ETHERSCAN_API_KEY: ""

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ./scripts/test-solidity.sh

  complete:
    runs-on: ubuntu-latest
    needs: [install, lint, test]

    steps:
      - name: Solidity tests successful
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          repository: ${{ github.repository }}
          event-type: solidity-tests-successful
